version: '3.7'

services:
  registry:
    image: registry:2
    # deploy:
    #   placement:
    #     constraints:
    #       - node.labels.registry == true
    environment:
      # REGISTRY_HTTP_ADDR: 0.0.0.0:443
      # REGISTRY_HTTP_TLS_CERTIFICATE: "/run/secrets/domain.crt"
      # REGISTRY_HTTP_TLS_KEY: "/run/secrets/domain.key"
      REGISTRY_HTTP_TLS_CERTIFICATE: /certs/domain.crt
      REGISTRY_HTTP_TLS_KEY: /certs/domain.key
      # REGISTRY_AUTH: htpasswd
      # REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
      # REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
    ports:
      - 5000:5000
      # - target: 443
      #   published: 443
    volumes:
      - type: bind
        source: /media/registry
        target: /var/lib/registry
      - type: bind
        source: /media/certs
        target: /certs

# secrets:
#   domain.crt:
#     external: true
#   domain.key:
#     external: true

