version: '3'

services:
  logstash:
    image: docker.elastic.co/logstash/logstash:6.2.4
    volumes:
      - /mount/general-data/logstash/pipeline/:/usr/share/logstash/pipeline/
#      - /mount/general-data/logstash/config/:/usr/share/logstash/config/
    restart: always

  elasticsearch1:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
    container_name: elasticsearch1
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /mount/general-data/elasticsearch1/:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - esnet

  elasticsearch2:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
    container_name: elasticsearch2
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=elasticsearch1"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /mount/general-data/elasticsearch2/:/usr/share/elasticsearch/data
    networks:
      - esnet

networks:
  esnet: