version: '3'

services:
   pm-db:
     image: mariadb
     environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: processmaker
       MYSQL_USER: processmaker
       MYSQL_PASSWORD: processmaker
     volumes:
       - /mount/general-data/pm-mysql:/var/lib/mysql

   pm:
     depends_on:
       - pm-db
     image: eltercera/docker-processmaker:3.2-php5.6-apache
     ports:
       - "8082:80"
     environment:
       HTTPD_SERVER_ADMIN: jonc@destini.com
       HTTPD_SERVER_ADMIN: 
       PHP_POST_MAX_SIZE: 10M
       PHP_UPLOAD_MAX_FILE_SIZE: 10M
     links:
       - pm-db
     volumes:
       - /mount/general-data/process-maker:/opt/processmaker

   admin:
     image: phpmyadmin/phpmyadmin
     depends_on:
       - pm-db
     environment:
       - PMA_ARBITRARY=1
     ports:
       - 8083:80
#     volumes:
#       - /sessions    
     links:
       - pm-db
