version: '3.1'

services:

   mysql:
     image: mysql:5.7
     environment:
       MYSQL_ROOT_PASSWORD: example
       MYSQL_USER: wpsql
       MYSQL_PASSWORD: wpsql
       MYSQL_DATABASE: wordpress
     volumes:
       - /mount/general-data/terry/mysql/:/var/lib/mysql  

   wordpress:
     image: wordpress
     depends_on:
       - mysql
     ports:
       - "5001:80"
     environment:
       WORDPRESS_DB_USER: wpsql
       WORDPRESS_DB_PASSWORD: wpsql

