version: '3.1'

services:
  kafka-1:
    image: confluentinc/cp-kafka:latest
    hostname: kafka1
    networks:
      - zoo_net
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181,zoo2:2181,zoo3:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:19092

networks:
  zoo_net:
