version: "3"

networks:
  jenkins_swarm:

services:
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - 8080:8080
    restart: always
    networks:
      - jenkins_swarm
    volumes:
      - jenkins_data:/var/jenkins_home

volumes:
  jenkins_data:
    driver: local
    driver_opts:
      type: nfs
      o: addr=10.0.0.5,rw
      device: ":/volume7/VM-File-Storage/{{.Service.Name}}-{{.Task.Slot}}-vol"

