version: '3.3'

services:
  frontend2:
    image: busybox:1.28
    command: /bin/top
    networks:
      - group2_net
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: dnsrr

  middle2:
    image: busybox:1.28
    command: /bin/top
    networks:
      - group2_net
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: dnsrr

  backend2:
    image: busybox:1.28
    command: /bin/top
    networks:
      - group2_net
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: dnsrr

networks:
  group2_net:

