version: '3.3'

services:
  bridge:
    image: busybox:1.28
    command: /bin/top
    networks:
      - group1_net
      - group2_net
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: dnsrr

networks:
  group1_net:
  group2_net:

